---
all:
  children:
    prod:
      vars:
        ansible_host: "{{ vault_vps_host }}"
        ansible_port: "{{ vault_vps_port }}"
        ansible_python_interpreter: /usr/bin/python3
        env_user: "{{ vault_vps_env_user }}"
        prov_user: "{{ vault_vps_prov_user }}"
      children:
        provision:
          hosts:
            prod_provision:
              ansible_user: "{{ prov_user }}"
        deploy:
          hosts:
            prod_deploy:
              ansible_user: "{{ env_user }}"
