---
all:
  hosts:
    prod:
      vars:
        ansible_host: "{{ lookup('ansible.builtin.env', 'VPS_HOST', default=Undefined) }}"
        ansible_port: "{{ lookup('ansible.builtin.env', 'VPS_PORT', default='Undefined') }}"
        ansible_ssh_private_key_file: /mnt/c/Users/nikol/.ovh/OvhVpsDefaultKey-eu-west-gra.pem
        ansible_python_interpreter: /usr/bin/python3
        env_user: "{{ lookup('ansible.builtin.env', 'VPS_ENVIRONMENT_USER', default=Undefined) }}"
        prov_user: "{{ lookup('ansible.builtin.env', 'VPS_PROVISION_USER', default=Undefined) }}"
      children:
        provision:
          hosts:
            prod_provision:
              ansible_user: "{{ prov_user }}"
        deploy:
          hosts:
            prod_deploy:
              ansible_user: "{{ env_user }}"