---
- name: Ensure key directories exist
  ansible.builtin.file:
    path: "{{ keys }}/{{ item }}"
    state: directory
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: "0700"
  loop: "{{ app_key_types }}"

- name: Generate private keys
  community.crypto.openssl_privatekey:
    path: "{{ keys }}/{{ item }}/{{ item }}-private.pem"
    type: RSA
    size: 2048
    format: pkcs8
    format_mismatch: convert
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: "0600"
  loop: "{{ app_key_types }}"
  no_log: true

- name: Generate public keys
  community.crypto.openssl_publickey:
    path: "{{ keys }}/{{ item }}/{{ item }}-public.pem"
    privatekey_path: "{{ keys }}/{{ item }}/{{ item }}-private.pem"
    format: PEM
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: "0644"
  loop: "{{ app_key_types }}"

- name: Render .env
  ansible.builtin.template:
    src: compose.env.j2
    dest: "{{ src }}/.env"
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: '0600'
  no_log: false
  register: bundle_env_file
