---
- name: Download migrations from S3
  ansible.builtin.command:
    argv:
      - aws
      - s3
      - sync
      - "s3://{{ vault_s3_bucket }}/{{ s3_prefix }}"
      - "{{ migration }}/"
      - "--region={{ vault_s3_region }}"
      - --delete
  register: bundle_s3_sync
  changed_when: "'download:' in bundle_s3_sync.stdout"
