---
- name: Migrations | Sync migrations from S3
  ansible.builtin.command:
    argv:
      - aws
      - s3
      - sync
      - "s3://{{ vault_s3_bucket }}/{{ s3_migrations_prefix }}"
      - "{{ src }}/db/migration/"
      - "--region={{ vault_s3_region }}"
      - --delete
      - --exact-timestamps
  register: migrations_s3_sync
  changed_when: "'download:' in migrations_s3_sync.stdout or 'delete:' in migrations_s3_sync.stdout"
