name: security

on:
  workflow_call:
    secrets:
      SEMGREP_APP_TOKEN:
        required: true

jobs:
  semgrep:
    name: Scanning Code
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v6.0.2
      - run: semgrep ci

