name: Build
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
jobs:
  build-and-push:
    name: Build & Push Docker image to AWS ECR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/refactor-etl-api'
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v6.0.2

      - name: Setup JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 #v5.0.0
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Extract and Tag Version
        id: versioning
        run: |
          chmod +x ./build/git-update.sh
          ./build/git-update.sh ${{ inputs.module_name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6.0.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261fc3d4806db1fa66a15cc11113c456db8870a7 #v2.1.0

      - name: Check AWS ECR for existing image
        run: |
          chmod +x ./build/ecr-update.sh
          ./build/ecr-update.sh ${{ inputs.module_name }} ${{ steps.versioning.outputs.git-tag }}

      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.module_name }}
          IMAGE_TAG: ${{ steps.versioning.outputs.git-tag }}
          PROFILE: prod
        working-directory: ./${{ inputs.module_name }}
        run: |
          docker build \
            --build-arg PROFILE=$PROFILE \
            --build-arg APP_VERSION=$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG