name: Test Ansible

on:
  push:
    branches:
      - chore/configure-ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_PORT: ${{ secrets.VPS_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Create vault password file
        run: |
          printf '%s' "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" | tr -d '\r' > /tmp/vault_pass.txt
          echo "vault password file: $(wc -c < /tmp/vault_pass.txt) bytes (expected 2774)"

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/vps_key
          chmod 600 ~/.ssh/vps_key
          ssh-keyscan -p "${{ secrets.VPS_PORT }}" "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Rollout
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventories/production/hosts.yml \
            --vault-password-file /tmp/vault_pass.txt \
            playbooks/deploy.yml \
            --private-key ~/.ssh/vps_key

      - name: Clean up secrets
        if: always()
        run: rm -f /tmp/vault_pass.txt ~/.ssh/vps_key